FROM php:7.4-apache

# Install dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends libpng-dev libjpeg-dev libxml2-dev libfreetype6-dev libzip-dev mariadb-client lftp curl unzip libmcrypt-dev \
    && pecl install mcrypt-1.0.4 \
    && docker-php-ext-enable mcrypt \
    && pecl install xdebug-2.9.8 \
    && docker-php-ext-enable xdebug \
    && echo 'xdebug.remote_enable=1' >> /usr/local/etc/php/php.ini \
    && echo 'xdebug.remote_autostart=1' >> /usr/local/etc/php/php.ini \
    && apt-get install -y vsftpd \
    && rm -rf /var/lib/apt/lists/*

# Create a user for FTP access
RUN useradd -m ftpuser && yes ftppassword | passwd ftpuser \
    && usermod -a -G www-data ftpuser

# Configure PHP Extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j "$(nproc)" gd opcache mysqli soap zip

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Set up FTP server (vsftpd)
COPY vsftpd.conf /etc/vsftpd.conf

# Download OpenCart
# Clone OpenCart
RUN apt-get update && apt-get install -y git \
    && git clone https://github.com/opencart/opencart.git \
    && cd opencart \
    && git checkout 2.3.0.2 \
    && cd .. \
    && mv opencart/upload/* . \
    && mv config-dist.php config.php \
    && mv admin/config-dist.php admin/config.php \
    && rm -rf opencart

# Create storage directory and set permissions
RUN mkdir -p /var/www/html/system/storage/logs \
    && chown -R www-data:www-data /var/www/html/system/storage \
    && chmod -R 755 /var/www/html/system/storage

# Set the ownership of all the files to the Apache user
RUN chown -R www-data:www-data /var/www/html

# Give ftpuser ownership of /var/www/html
RUN chown -R ftpuser:www-data /var/www/html \
    && chmod -R 777 /var/www/html \
    && chmod 777 /var/www/html/config.php \
    && chmod 777 /var/www/html/admin/config.php \
    && chmod -R 777 /var/www/html/image \
    && chmod -R 777 /var/www/html/system/storage

# Start vsftpd in the background
CMD service vsftpd start && apache2-foreground
